name: amubavisual_weddingphoto
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_widget_from_html: ^0.15.3
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_gallery_saver_plus: ^3.0.5
  intl: null
  photo_view: ^0.15.0
  upgrader: ^11.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/visual-logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
